/*
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.security.guardium;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ibm.security.guardium.Assetsv3ChildCategory;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.ibm.security.JSON;

/**
 * SubCategory - Sub Category Data for Manage Asset Filter Panel.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-12T11:32:35.296131573-07:00[America/Los_Angeles]", comments = "Generator version: 7.16.0")
public class Assetsv3SubCategory {
  public static final String SERIALIZED_NAME_CHILDREN_CATEGORY = "children_category";
  @SerializedName(SERIALIZED_NAME_CHILDREN_CATEGORY)
  @javax.annotation.Nullable
  private List<Assetsv3ChildCategory> childrenCategory = new ArrayList<>();

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public Assetsv3SubCategory() {
  }

  public Assetsv3SubCategory childrenCategory(@javax.annotation.Nullable List<Assetsv3ChildCategory> childrenCategory) {
    this.childrenCategory = childrenCategory;
    return this;
  }

  public Assetsv3SubCategory addChildrenCategoryItem(Assetsv3ChildCategory childrenCategoryItem) {
    if (this.childrenCategory == null) {
      this.childrenCategory = new ArrayList<>();
    }
    this.childrenCategory.add(childrenCategoryItem);
    return this;
  }

  /**
   * Get childrenCategory
   * @return childrenCategory
   */
  @javax.annotation.Nullable
  public List<Assetsv3ChildCategory> getChildrenCategory() {
    return childrenCategory;
  }

  public void setChildrenCategory(@javax.annotation.Nullable List<Assetsv3ChildCategory> childrenCategory) {
    this.childrenCategory = childrenCategory;
  }


  public Assetsv3SubCategory id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public Assetsv3SubCategory name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Assetsv3SubCategory assetsv3SubCategory = (Assetsv3SubCategory) o;
    return Objects.equals(this.childrenCategory, assetsv3SubCategory.childrenCategory) &&
        Objects.equals(this.id, assetsv3SubCategory.id) &&
        Objects.equals(this.name, assetsv3SubCategory.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(childrenCategory, id, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Assetsv3SubCategory {\n");
    sb.append("    childrenCategory: ").append(toIndentedString(childrenCategory)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("children_category", "id", "name"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Assetsv3SubCategory
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Assetsv3SubCategory.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in Assetsv3SubCategory is not found in the empty JSON string", Assetsv3SubCategory.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Assetsv3SubCategory.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Assetsv3SubCategory` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("children_category") != null && !jsonObj.get("children_category").isJsonNull()) {
        JsonArray jsonArraychildrenCategory = jsonObj.getAsJsonArray("children_category");
        if (jsonArraychildrenCategory != null) {
          // ensure the json data is an array
          if (!jsonObj.get("children_category").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `children_category` to be an array in the JSON string but got `%s`", jsonObj.get("children_category").toString()));
          }

          // validate the optional field `children_category` (array)
          for (int i = 0; i < jsonArraychildrenCategory.size(); i++) {
            Assetsv3ChildCategory.validateJsonElement(jsonArraychildrenCategory.get(i));
          };
        }
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Assetsv3SubCategory.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Assetsv3SubCategory' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Assetsv3SubCategory> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Assetsv3SubCategory.class));

       return (TypeAdapter<T>) new TypeAdapter<Assetsv3SubCategory>() {
           @Override
           public void write(JsonWriter out, Assetsv3SubCategory value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Assetsv3SubCategory read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Assetsv3SubCategory given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Assetsv3SubCategory
   * @throws IOException if the JSON string is invalid with respect to Assetsv3SubCategory
   */
  public static Assetsv3SubCategory fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Assetsv3SubCategory.class);
  }

  /**
   * Convert an instance of Assetsv3SubCategory to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

