/*
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.security.guardium;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ibm.security.guardium.Assetsv3FilterSubCatagoryChild;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.ibm.security.JSON;

/**
 * Assetsv3FilterSubCatagory
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-12T11:32:35.296131573-07:00[America/Los_Angeles]", comments = "Generator version: 7.16.0")
public class Assetsv3FilterSubCatagory {
  public static final String SERIALIZED_NAME_SELECTED_CHILDREN_LIST = "selected_children_list";
  @SerializedName(SERIALIZED_NAME_SELECTED_CHILDREN_LIST)
  @javax.annotation.Nullable
  private List<Assetsv3FilterSubCatagoryChild> selectedChildrenList = new ArrayList<>();

  public static final String SERIALIZED_NAME_SUB_CATAGORY_ID = "sub_catagory_id";
  @SerializedName(SERIALIZED_NAME_SUB_CATAGORY_ID)
  @javax.annotation.Nullable
  private String subCatagoryId;

  public static final String SERIALIZED_NAME_SUB_CATEGORY_VALUE = "sub_category_value";
  @SerializedName(SERIALIZED_NAME_SUB_CATEGORY_VALUE)
  @javax.annotation.Nullable
  private String subCategoryValue;

  public Assetsv3FilterSubCatagory() {
  }

  public Assetsv3FilterSubCatagory selectedChildrenList(@javax.annotation.Nullable List<Assetsv3FilterSubCatagoryChild> selectedChildrenList) {
    this.selectedChildrenList = selectedChildrenList;
    return this;
  }

  public Assetsv3FilterSubCatagory addSelectedChildrenListItem(Assetsv3FilterSubCatagoryChild selectedChildrenListItem) {
    if (this.selectedChildrenList == null) {
      this.selectedChildrenList = new ArrayList<>();
    }
    this.selectedChildrenList.add(selectedChildrenListItem);
    return this;
  }

  /**
   * Get selectedChildrenList
   * @return selectedChildrenList
   */
  @javax.annotation.Nullable
  public List<Assetsv3FilterSubCatagoryChild> getSelectedChildrenList() {
    return selectedChildrenList;
  }

  public void setSelectedChildrenList(@javax.annotation.Nullable List<Assetsv3FilterSubCatagoryChild> selectedChildrenList) {
    this.selectedChildrenList = selectedChildrenList;
  }


  public Assetsv3FilterSubCatagory subCatagoryId(@javax.annotation.Nullable String subCatagoryId) {
    this.subCatagoryId = subCatagoryId;
    return this;
  }

  /**
   * Get subCatagoryId
   * @return subCatagoryId
   */
  @javax.annotation.Nullable
  public String getSubCatagoryId() {
    return subCatagoryId;
  }

  public void setSubCatagoryId(@javax.annotation.Nullable String subCatagoryId) {
    this.subCatagoryId = subCatagoryId;
  }


  public Assetsv3FilterSubCatagory subCategoryValue(@javax.annotation.Nullable String subCategoryValue) {
    this.subCategoryValue = subCategoryValue;
    return this;
  }

  /**
   * Get subCategoryValue
   * @return subCategoryValue
   */
  @javax.annotation.Nullable
  public String getSubCategoryValue() {
    return subCategoryValue;
  }

  public void setSubCategoryValue(@javax.annotation.Nullable String subCategoryValue) {
    this.subCategoryValue = subCategoryValue;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Assetsv3FilterSubCatagory assetsv3FilterSubCatagory = (Assetsv3FilterSubCatagory) o;
    return Objects.equals(this.selectedChildrenList, assetsv3FilterSubCatagory.selectedChildrenList) &&
        Objects.equals(this.subCatagoryId, assetsv3FilterSubCatagory.subCatagoryId) &&
        Objects.equals(this.subCategoryValue, assetsv3FilterSubCatagory.subCategoryValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(selectedChildrenList, subCatagoryId, subCategoryValue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Assetsv3FilterSubCatagory {\n");
    sb.append("    selectedChildrenList: ").append(toIndentedString(selectedChildrenList)).append("\n");
    sb.append("    subCatagoryId: ").append(toIndentedString(subCatagoryId)).append("\n");
    sb.append("    subCategoryValue: ").append(toIndentedString(subCategoryValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("selected_children_list", "sub_catagory_id", "sub_category_value"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Assetsv3FilterSubCatagory
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Assetsv3FilterSubCatagory.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in Assetsv3FilterSubCatagory is not found in the empty JSON string", Assetsv3FilterSubCatagory.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Assetsv3FilterSubCatagory.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Assetsv3FilterSubCatagory` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("selected_children_list") != null && !jsonObj.get("selected_children_list").isJsonNull()) {
        JsonArray jsonArrayselectedChildrenList = jsonObj.getAsJsonArray("selected_children_list");
        if (jsonArrayselectedChildrenList != null) {
          // ensure the json data is an array
          if (!jsonObj.get("selected_children_list").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `selected_children_list` to be an array in the JSON string but got `%s`", jsonObj.get("selected_children_list").toString()));
          }

          // validate the optional field `selected_children_list` (array)
          for (int i = 0; i < jsonArrayselectedChildrenList.size(); i++) {
            Assetsv3FilterSubCatagoryChild.validateJsonElement(jsonArrayselectedChildrenList.get(i));
          };
        }
      }
      if ((jsonObj.get("sub_catagory_id") != null && !jsonObj.get("sub_catagory_id").isJsonNull()) && !jsonObj.get("sub_catagory_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `sub_catagory_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sub_catagory_id").toString()));
      }
      if ((jsonObj.get("sub_category_value") != null && !jsonObj.get("sub_category_value").isJsonNull()) && !jsonObj.get("sub_category_value").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `sub_category_value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sub_category_value").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Assetsv3FilterSubCatagory.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Assetsv3FilterSubCatagory' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Assetsv3FilterSubCatagory> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Assetsv3FilterSubCatagory.class));

       return (TypeAdapter<T>) new TypeAdapter<Assetsv3FilterSubCatagory>() {
           @Override
           public void write(JsonWriter out, Assetsv3FilterSubCatagory value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Assetsv3FilterSubCatagory read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Assetsv3FilterSubCatagory given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Assetsv3FilterSubCatagory
   * @throws IOException if the JSON string is invalid with respect to Assetsv3FilterSubCatagory
   */
  public static Assetsv3FilterSubCatagory fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Assetsv3FilterSubCatagory.class);
  }

  /**
   * Convert an instance of Assetsv3FilterSubCatagory to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

