/*
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.security.guardium;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.ibm.security.JSON;

/**
 * Get folders from the integratioin provided. The configuration properties vary by integration and must match the required content.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-12T11:32:35.296131573-07:00[America/Los_Angeles]", comments = "Generator version: 7.16.0")
public class Notificationsv3GetFoldersRequest {
  public static final String SERIALIZED_NAME_FOLDER_NAME = "folder_name";
  @SerializedName(SERIALIZED_NAME_FOLDER_NAME)
  @javax.annotation.Nullable
  private String folderName;

  public static final String SERIALIZED_NAME_INTEGRATION_ID = "integration_id";
  @SerializedName(SERIALIZED_NAME_INTEGRATION_ID)
  @javax.annotation.Nullable
  private String integrationId;

  public Notificationsv3GetFoldersRequest() {
  }

  public Notificationsv3GetFoldersRequest folderName(@javax.annotation.Nullable String folderName) {
    this.folderName = folderName;
    return this;
  }

  /**
   * The folder_name field is provided to fetch all folders in the folder_name provided.
   * @return folderName
   */
  @javax.annotation.Nullable
  public String getFolderName() {
    return folderName;
  }

  public void setFolderName(@javax.annotation.Nullable String folderName) {
    this.folderName = folderName;
  }


  public Notificationsv3GetFoldersRequest integrationId(@javax.annotation.Nullable String integrationId) {
    this.integrationId = integrationId;
    return this;
  }

  /**
   * The integration id to get the folders for.
   * @return integrationId
   */
  @javax.annotation.Nullable
  public String getIntegrationId() {
    return integrationId;
  }

  public void setIntegrationId(@javax.annotation.Nullable String integrationId) {
    this.integrationId = integrationId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Notificationsv3GetFoldersRequest notificationsv3GetFoldersRequest = (Notificationsv3GetFoldersRequest) o;
    return Objects.equals(this.folderName, notificationsv3GetFoldersRequest.folderName) &&
        Objects.equals(this.integrationId, notificationsv3GetFoldersRequest.integrationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(folderName, integrationId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Notificationsv3GetFoldersRequest {\n");
    sb.append("    folderName: ").append(toIndentedString(folderName)).append("\n");
    sb.append("    integrationId: ").append(toIndentedString(integrationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("folder_name", "integration_id"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Notificationsv3GetFoldersRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Notificationsv3GetFoldersRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in Notificationsv3GetFoldersRequest is not found in the empty JSON string", Notificationsv3GetFoldersRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Notificationsv3GetFoldersRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Notificationsv3GetFoldersRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("folder_name") != null && !jsonObj.get("folder_name").isJsonNull()) && !jsonObj.get("folder_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `folder_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("folder_name").toString()));
      }
      if ((jsonObj.get("integration_id") != null && !jsonObj.get("integration_id").isJsonNull()) && !jsonObj.get("integration_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `integration_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("integration_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Notificationsv3GetFoldersRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Notificationsv3GetFoldersRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Notificationsv3GetFoldersRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Notificationsv3GetFoldersRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<Notificationsv3GetFoldersRequest>() {
           @Override
           public void write(JsonWriter out, Notificationsv3GetFoldersRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Notificationsv3GetFoldersRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Notificationsv3GetFoldersRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Notificationsv3GetFoldersRequest
   * @throws IOException if the JSON string is invalid with respect to Notificationsv3GetFoldersRequest
   */
  public static Notificationsv3GetFoldersRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Notificationsv3GetFoldersRequest.class);
  }

  /**
   * Convert an instance of Notificationsv3GetFoldersRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

