/*
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.security.guardium;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ibm.security.guardium.Riskanalyticscontrollerv3RiskFeedback;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.ibm.security.JSON;

/**
 * GetRiskFeedbackResponse is the response object for GetRiskFeedback API.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-12T11:32:35.296131573-07:00[America/Los_Angeles]", comments = "Generator version: 7.16.0")
public class Riskanalyticscontrollerv3GetRiskFeedbackResponse {
  public static final String SERIALIZED_NAME_RISK_FEEDBACKS = "risk_feedbacks";
  @SerializedName(SERIALIZED_NAME_RISK_FEEDBACKS)
  @javax.annotation.Nullable
  private List<Riskanalyticscontrollerv3RiskFeedback> riskFeedbacks = new ArrayList<>();

  public Riskanalyticscontrollerv3GetRiskFeedbackResponse() {
  }

  public Riskanalyticscontrollerv3GetRiskFeedbackResponse riskFeedbacks(@javax.annotation.Nullable List<Riskanalyticscontrollerv3RiskFeedback> riskFeedbacks) {
    this.riskFeedbacks = riskFeedbacks;
    return this;
  }

  public Riskanalyticscontrollerv3GetRiskFeedbackResponse addRiskFeedbacksItem(Riskanalyticscontrollerv3RiskFeedback riskFeedbacksItem) {
    if (this.riskFeedbacks == null) {
      this.riskFeedbacks = new ArrayList<>();
    }
    this.riskFeedbacks.add(riskFeedbacksItem);
    return this;
  }

  /**
   * List of risk_feedbacks in status NEW.
   * @return riskFeedbacks
   */
  @javax.annotation.Nullable
  public List<Riskanalyticscontrollerv3RiskFeedback> getRiskFeedbacks() {
    return riskFeedbacks;
  }

  public void setRiskFeedbacks(@javax.annotation.Nullable List<Riskanalyticscontrollerv3RiskFeedback> riskFeedbacks) {
    this.riskFeedbacks = riskFeedbacks;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Riskanalyticscontrollerv3GetRiskFeedbackResponse riskanalyticscontrollerv3GetRiskFeedbackResponse = (Riskanalyticscontrollerv3GetRiskFeedbackResponse) o;
    return Objects.equals(this.riskFeedbacks, riskanalyticscontrollerv3GetRiskFeedbackResponse.riskFeedbacks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(riskFeedbacks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Riskanalyticscontrollerv3GetRiskFeedbackResponse {\n");
    sb.append("    riskFeedbacks: ").append(toIndentedString(riskFeedbacks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("risk_feedbacks"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Riskanalyticscontrollerv3GetRiskFeedbackResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Riskanalyticscontrollerv3GetRiskFeedbackResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in Riskanalyticscontrollerv3GetRiskFeedbackResponse is not found in the empty JSON string", Riskanalyticscontrollerv3GetRiskFeedbackResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Riskanalyticscontrollerv3GetRiskFeedbackResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Riskanalyticscontrollerv3GetRiskFeedbackResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("risk_feedbacks") != null && !jsonObj.get("risk_feedbacks").isJsonNull()) {
        JsonArray jsonArrayriskFeedbacks = jsonObj.getAsJsonArray("risk_feedbacks");
        if (jsonArrayriskFeedbacks != null) {
          // ensure the json data is an array
          if (!jsonObj.get("risk_feedbacks").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `risk_feedbacks` to be an array in the JSON string but got `%s`", jsonObj.get("risk_feedbacks").toString()));
          }

          // validate the optional field `risk_feedbacks` (array)
          for (int i = 0; i < jsonArrayriskFeedbacks.size(); i++) {
            Riskanalyticscontrollerv3RiskFeedback.validateJsonElement(jsonArrayriskFeedbacks.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Riskanalyticscontrollerv3GetRiskFeedbackResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Riskanalyticscontrollerv3GetRiskFeedbackResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Riskanalyticscontrollerv3GetRiskFeedbackResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Riskanalyticscontrollerv3GetRiskFeedbackResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<Riskanalyticscontrollerv3GetRiskFeedbackResponse>() {
           @Override
           public void write(JsonWriter out, Riskanalyticscontrollerv3GetRiskFeedbackResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Riskanalyticscontrollerv3GetRiskFeedbackResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Riskanalyticscontrollerv3GetRiskFeedbackResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Riskanalyticscontrollerv3GetRiskFeedbackResponse
   * @throws IOException if the JSON string is invalid with respect to Riskanalyticscontrollerv3GetRiskFeedbackResponse
   */
  public static Riskanalyticscontrollerv3GetRiskFeedbackResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Riskanalyticscontrollerv3GetRiskFeedbackResponse.class);
  }

  /**
   * Convert an instance of Riskanalyticscontrollerv3GetRiskFeedbackResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

