/*
 * IBM Guardium Data Security Center
 * Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.security.guardium;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ibm.security.guardium.Riskanalyticscontrollerv3Filter;
import com.ibm.security.guardium.Riskanalyticscontrollerv3OrderBy;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.ibm.security.JSON;

/**
 * CardSettings a object to display each card of risks.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-12T11:32:35.296131573-07:00[America/Los_Angeles]", comments = "Generator version: 7.16.0")
public class Riskanalyticscontrollerv3CardSettings {
  public static final String SERIALIZED_NAME_FILTERS = "filters";
  @SerializedName(SERIALIZED_NAME_FILTERS)
  @javax.annotation.Nullable
  private List<Riskanalyticscontrollerv3Filter> filters = new ArrayList<>();

  public static final String SERIALIZED_NAME_HEADERS = "headers";
  @SerializedName(SERIALIZED_NAME_HEADERS)
  @javax.annotation.Nullable
  private List<String> headers = new ArrayList<>();

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_ORDER_BY = "order_by";
  @SerializedName(SERIALIZED_NAME_ORDER_BY)
  @javax.annotation.Nullable
  private Riskanalyticscontrollerv3OrderBy orderBy = Riskanalyticscontrollerv3OrderBy.UNDEFINED_ORDER_BY;

  public static final String SERIALIZED_NAME_SEQUENCE_ORDER = "sequence_order";
  @SerializedName(SERIALIZED_NAME_SEQUENCE_ORDER)
  @javax.annotation.Nullable
  private Integer sequenceOrder;

  public static final String SERIALIZED_NAME_SORTED_BY = "sorted_by";
  @SerializedName(SERIALIZED_NAME_SORTED_BY)
  @javax.annotation.Nullable
  private String sortedBy;

  public Riskanalyticscontrollerv3CardSettings() {
  }

  public Riskanalyticscontrollerv3CardSettings filters(@javax.annotation.Nullable List<Riskanalyticscontrollerv3Filter> filters) {
    this.filters = filters;
    return this;
  }

  public Riskanalyticscontrollerv3CardSettings addFiltersItem(Riskanalyticscontrollerv3Filter filtersItem) {
    if (this.filters == null) {
      this.filters = new ArrayList<>();
    }
    this.filters.add(filtersItem);
    return this;
  }

  /**
   * Filters - list if filters to view the risk.
   * @return filters
   */
  @javax.annotation.Nullable
  public List<Riskanalyticscontrollerv3Filter> getFilters() {
    return filters;
  }

  public void setFilters(@javax.annotation.Nullable List<Riskanalyticscontrollerv3Filter> filters) {
    this.filters = filters;
  }


  public Riskanalyticscontrollerv3CardSettings headers(@javax.annotation.Nullable List<String> headers) {
    this.headers = headers;
    return this;
  }

  public Riskanalyticscontrollerv3CardSettings addHeadersItem(String headersItem) {
    if (this.headers == null) {
      this.headers = new ArrayList<>();
    }
    this.headers.add(headersItem);
    return this;
  }

  /**
   * Headers - list of headers to view the risks.
   * @return headers
   */
  @javax.annotation.Nullable
  public List<String> getHeaders() {
    return headers;
  }

  public void setHeaders(@javax.annotation.Nullable List<String> headers) {
    this.headers = headers;
  }


  public Riskanalyticscontrollerv3CardSettings id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Id of the settings.
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public Riskanalyticscontrollerv3CardSettings name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Name of the view - nls value in case its first time for user.
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public Riskanalyticscontrollerv3CardSettings orderBy(@javax.annotation.Nullable Riskanalyticscontrollerv3OrderBy orderBy) {
    this.orderBy = orderBy;
    return this;
  }

  /**
   * Get orderBy
   * @return orderBy
   */
  @javax.annotation.Nullable
  public Riskanalyticscontrollerv3OrderBy getOrderBy() {
    return orderBy;
  }

  public void setOrderBy(@javax.annotation.Nullable Riskanalyticscontrollerv3OrderBy orderBy) {
    this.orderBy = orderBy;
  }


  public Riskanalyticscontrollerv3CardSettings sequenceOrder(@javax.annotation.Nullable Integer sequenceOrder) {
    this.sequenceOrder = sequenceOrder;
    return this;
  }

  /**
   * Sequence  order of the view(box) of the risks.
   * @return sequenceOrder
   */
  @javax.annotation.Nullable
  public Integer getSequenceOrder() {
    return sequenceOrder;
  }

  public void setSequenceOrder(@javax.annotation.Nullable Integer sequenceOrder) {
    this.sequenceOrder = sequenceOrder;
  }


  public Riskanalyticscontrollerv3CardSettings sortedBy(@javax.annotation.Nullable String sortedBy) {
    this.sortedBy = sortedBy;
    return this;
  }

  /**
   * Sorted by header_id to sort the risks in the view by.
   * @return sortedBy
   */
  @javax.annotation.Nullable
  public String getSortedBy() {
    return sortedBy;
  }

  public void setSortedBy(@javax.annotation.Nullable String sortedBy) {
    this.sortedBy = sortedBy;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Riskanalyticscontrollerv3CardSettings riskanalyticscontrollerv3CardSettings = (Riskanalyticscontrollerv3CardSettings) o;
    return Objects.equals(this.filters, riskanalyticscontrollerv3CardSettings.filters) &&
        Objects.equals(this.headers, riskanalyticscontrollerv3CardSettings.headers) &&
        Objects.equals(this.id, riskanalyticscontrollerv3CardSettings.id) &&
        Objects.equals(this.name, riskanalyticscontrollerv3CardSettings.name) &&
        Objects.equals(this.orderBy, riskanalyticscontrollerv3CardSettings.orderBy) &&
        Objects.equals(this.sequenceOrder, riskanalyticscontrollerv3CardSettings.sequenceOrder) &&
        Objects.equals(this.sortedBy, riskanalyticscontrollerv3CardSettings.sortedBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(filters, headers, id, name, orderBy, sequenceOrder, sortedBy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Riskanalyticscontrollerv3CardSettings {\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    orderBy: ").append(toIndentedString(orderBy)).append("\n");
    sb.append("    sequenceOrder: ").append(toIndentedString(sequenceOrder)).append("\n");
    sb.append("    sortedBy: ").append(toIndentedString(sortedBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("filters", "headers", "id", "name", "order_by", "sequence_order", "sorted_by"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Riskanalyticscontrollerv3CardSettings
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Riskanalyticscontrollerv3CardSettings.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in Riskanalyticscontrollerv3CardSettings is not found in the empty JSON string", Riskanalyticscontrollerv3CardSettings.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Riskanalyticscontrollerv3CardSettings.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Riskanalyticscontrollerv3CardSettings` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("filters") != null && !jsonObj.get("filters").isJsonNull()) {
        JsonArray jsonArrayfilters = jsonObj.getAsJsonArray("filters");
        if (jsonArrayfilters != null) {
          // ensure the json data is an array
          if (!jsonObj.get("filters").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `filters` to be an array in the JSON string but got `%s`", jsonObj.get("filters").toString()));
          }

          // validate the optional field `filters` (array)
          for (int i = 0; i < jsonArrayfilters.size(); i++) {
            Riskanalyticscontrollerv3Filter.validateJsonElement(jsonArrayfilters.get(i));
          };
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("headers") != null && !jsonObj.get("headers").isJsonNull() && !jsonObj.get("headers").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `headers` to be an array in the JSON string but got `%s`", jsonObj.get("headers").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // validate the optional field `order_by`
      if (jsonObj.get("order_by") != null && !jsonObj.get("order_by").isJsonNull()) {
        Riskanalyticscontrollerv3OrderBy.validateJsonElement(jsonObj.get("order_by"));
      }
      if ((jsonObj.get("sorted_by") != null && !jsonObj.get("sorted_by").isJsonNull()) && !jsonObj.get("sorted_by").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `sorted_by` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sorted_by").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Riskanalyticscontrollerv3CardSettings.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Riskanalyticscontrollerv3CardSettings' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Riskanalyticscontrollerv3CardSettings> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Riskanalyticscontrollerv3CardSettings.class));

       return (TypeAdapter<T>) new TypeAdapter<Riskanalyticscontrollerv3CardSettings>() {
           @Override
           public void write(JsonWriter out, Riskanalyticscontrollerv3CardSettings value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Riskanalyticscontrollerv3CardSettings read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Riskanalyticscontrollerv3CardSettings given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Riskanalyticscontrollerv3CardSettings
   * @throws IOException if the JSON string is invalid with respect to Riskanalyticscontrollerv3CardSettings
   */
  public static Riskanalyticscontrollerv3CardSettings fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Riskanalyticscontrollerv3CardSettings.class);
  }

  /**
   * Convert an instance of Riskanalyticscontrollerv3CardSettings to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

